apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

